Repository microsoft/ApplicationInsights-Java, pull requests merged in 2018-03, with the labels that each got.

#582 Fix customizing pom.xml in Gradle build
  core/build.gradle
  gradle/publishing.gradle
  gradlew
  logging/logging.gradle
  web/build.gradle
Labels: bug

#567 Add Instrumentation to Collect Missing HTTP Parameters
  CHANGELOG.md
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java
Labels: bug

#512 Rethrow threaddeath
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/jmx/JmxConnectorLoader.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/StatementClassDataDataProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationBuilderFactory.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlParserUtils.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
  agent/src/test/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilderTest.java
  collectd/src/main/java/com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter.java
  core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
  core/src/main/java/com/microsoft/applicationinsights/channel/concrete/inprocess/InProcessTelemetryChannel.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/ArgsFormatter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
  core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionFileSystemOutput.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionNetworkOutput.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/GzipTelemetrySerializer.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImpl.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling/AdaptiveTelemetrySampler.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling/SamplingScoreGenerator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetrySamplerInitializer.java
  core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractPerformanceCounterModule.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersFactory.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainer.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessBuiltInPerformanceCountersFactory.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessCpuPerformanceCounter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/TraceTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseCoordinator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataSender.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java
  core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
  core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java
  samples/src/plugins/java/com/microsoft/applicationinsights/sample/plugins/GitBuildInfoContextInitializer.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
Labels: Best Practices

#604 add MaxInstantRetry XML Element in Channel configuration
  core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
Labels: enhancement

#602 Enable Cold Start
  agent/build.gradle
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/CodeInjector.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/exceptions/RuntimeExceptionProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/ConfigRuntimeExceptionDataBuilder.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling/FixedRateTelemetrySampler.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilder.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetrySamplerInitializer.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersFactory.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainer.java
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessCpuPerformanceCounter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/processor/TraceTelemetryFilter.java
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseCoordinator.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
Labels: enhancement

#516 Added check for TelemetryConfiguration#getInstrumentationKey emptiness
  core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
Labels: enhancement

#614 Change JmxMetricPerformanceCounter
  core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
Labels: bug

#618 support real time logging
  core/src/main/java/com/microsoft/applicationinsights/internal/logger/DefaultLogFileProxy.java
Labels: bug

#624 Fix incorrect success flag set while capturing http dependency
  CHANGELOG.md
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
Labels: bug
