Repository microsoft/ApplicationInsights-Java, pull requests merged in 2018-06, with the labels that each got.

#680 fixing the http dependency collection issue with NetFlix Zuul
  CHANGELOG.md
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler.java
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
  core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
Labels: bug

#689 Add cleanup step to test
  core/src/test/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocatorTest.java
Labels: Tests

#692 closed open stream so temp test resource files can be deleted
  core/src/test/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocatorTest.java
Labels: Tests, bug
