Repository microsoft/ApplicationInsights-Java, pull requests merged in 2019-04, with the labels that each got.

#893 include gradle sources/javadoc for better experience with IDEs
  gradle/wrapper/gradle-wrapper.properties
Labels: Build, enhancement

#904 Fix qps invariant version from 2 -> 1
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
Labels: bug

#903 Increase persistent http connection validation period
  CHANGELOG.md
  core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java
Labels: bug

#901 Reset CDS Profile fetch counters + Introduce generic PeriodTaskExecutor
  core/src/main/java/com/microsoft/applicationinsights/internal/profile/CdsRetryPolicy.java
  core/src/main/java/com/microsoft/applicationinsights/internal/util/PeriodicTaskManager.java
  core/src/test/java/com/microsoft/applicationinsights/internal/profile/CdsRetryPolicyTests.java
  core/src/test/java/com/microsoft/applicationinsights/internal/util/PeriodicRunnableTaskManagerTests.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcherTests.java
Labels: enhancement

#908 Upgrade gradle to 5.3.1
  CHANGELOG.md
  agent/build.gradle
  azure-application-insights-spring-boot-starter/build.gradle
  build.gradle
  collectd/build.gradle
  core/build.gradle
  core/native.gradle
  distributions/build.gradle
  gradle/common-java.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  test/smoke/testApps/build.gradle
  web/build.gradle
Labels: Build
