Repository microsoft/ApplicationInsights-Java, pull requests merged in 2019-03, with the labels that each got.

#820 Add Async Listener Strucutre
  web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
Labels: enhancement

#826 Remove duplicate provider
  CHANGELOG.md
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassDataProvider.java
Labels: bug

#827 Add Async Listener Implementation
  web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListenerTest.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java
Labels: enhancement

#830 Final Integration: Async Listener
  CHANGELOG.md
  test/webapps/bookstore-spring/src/main/java/com/springapp/mvc/extensions/WebRequestRunIdTelemetryModule.java
  web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
  web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
  web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
  web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModule.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
  web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
  web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/ThreadContextTests.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilterTests.java
  web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java
Labels: enhancement

#836 Async Request Tracking and Correlation Integration Tests
  settings.gradle
  test/smoke/framework/fakeIngestion/standalone/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServer.java
  test/smoke/testApps/SpringBootTest/build.gradle
  test/smoke/testApps/SpringBootTest/src/main/java/com/SpringBootApp.java
  test/smoke/testApps/SpringBootTest/src/main/java/com/springbootstartertest/controller/TestController.java
  test/smoke/testApps/SpringBootTest/src/main/resources/application.properties
  test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java
  test/smoke/testApps/SpringBootTest/src/smokeTest/resources/appServers.txt
  web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java
Labels: Tests

#842 disable unsafe xml features
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
Labels: Security Issue

#846 Instrument new version of postgres - Fix postgresql prepared statement instrumentation
  CHANGELOG.md
  agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java
Labels: enhancement

#881 Fix SDK Version sent from QuickPulse channel
  CHANGELOG.md
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
  core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcherTests.java
Labels: bug

#883 Add implementation of dependency metric collection for Livemetrics
  CHANGELOG.md
  core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java
Labels: bug
